# ===============================
# Application
# ===============================
spring.application.name=flipkart-clone-backend
server.port=8081

# ===============================
# PostgreSQL Database (Docker)
# ===============================
spring.datasource.url=jdbc:postgresql://postgres:5432/flipkartdb
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Dialect auto-detect hota hai (optional)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JWT Security
# ===============================
jwt.secret=THIS_IS_MY_SUPER_SECRET_KEY_1234567890
jwt.expiration=3600000

# ===============================
# Swagger
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# Actuator / Monitoring
# ===============================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always